<article class="bugdoc">
    <h2 class="bugdoc-title" id="Bug-Doc:PE1049">PE1049: 错误的异常抛出/捕获</h2>
    <h3>错误的异常抛出/捕获。</h3>
    <section id="tip">
     <h4 style="border-top: 0pt; padding: 0pt 4pt 4pt 4pt;">缺陷信息</h4>
                <dl>
                    <dt>缺陷ID</dt>
                    <dd>PE1049</dd>
                    <dt>标签</dt>
                    <dd>CPP</dd>
                    <dt>目录</dt>
                    <dd>Checkers/CPP</dd>
                    <dt>作者</dt>
                    <dd>pinpoint</dd>
                </dl>
    <h4>缺陷描述</h4>
<p>在析够函数里抛异常是危险的，因为析够函数不是程序员主动调用的，很有可能异常没有被catch。</p>
<p>异常值指向释放过的内存。</p>
<p>性能问题，多余的异常信息复制。使用throw exception重新抛出相同异常会复制exception,应该使用throw;替代throw exception免去多余的异常信息的复制。</p>
<p>性能问题，应该使用引用而不是值接收异常信息，这样可以省去不必要的异常信息的复制。</p>
<p>在没有声明会抛出异常的函数抛异常。</p>
<h4>漏洞利用威胁</h4>
<p>高</p>

    </section>
</article>
