<article class="bugdoc">
    <h2 class="bugdoc-title" id="Bug-Doc:PE1049">PE1049: Incorrect exception throw/catch</h2>
    <h3>Incorrect exception throw/catch</h3>
    <section id="tip">
     <h4 style="border-top: 0pt; padding: 0pt 4pt 4pt 4pt;">Bug info</h4>
                <dl>
                    <dt>BugTypeID</dt>
                    <dd>PE1049</dd>
                    <dt>Tags</dt>
                    <dd>CPP</dd>
                    <dt>Category</dt>
                    <dd>Checkers/CPP</dd>
                    <dt>Authors</dt>
                    <dd>pinpoint</dd>
                </dl>
    <h4>Description</h4>
<p>Throughing exception in a destructor is dangerous because the catching of the exception is likely to miss.</p>
<p>Exception points at deallocated memory.</p>
<p>Performance issue. Throwing a copy of the caught exception instead of rethrowing the original exception. Rethrowing an exception with 'throw  + varname;' creates an unnecessary copy. To rethrow the caught exception without unnecessary copying or slicing, use a bare throw.</p>
<p>Performance issue. Exception should be caught by reference instead of value to avoid memory copying.</p>
<p>Exception thrown in function declared not to throw exceptions.</p>
<h4>Likelihood of Exploit</h4>
<p>high</p>

    </section>
</article>
