<article class="bugdoc">
    <h2 class="bugdoc-title" id="Bug-Doc:PE22316">PE22316: B001</h2>
    <h3>B001</h3>
    <section id="tip">
     <h4 style="border-top: 0pt; padding: 0pt 4pt 4pt 4pt;">缺陷信息</h4>
                <dl>
                    <dt>缺陷ID</dt>
                    <dd>PE22316</dd>
                    <dt>标签</dt>
                    <dd>flake8</dd>
                    <dt>目录</dt>
                    <dd>Code style and efficiency</dd>
                    <dt>作者</dt>
                    <dd>pinpoint</dd>
                </dl>
    <h2>缺陷成因</h2>

<pre><code>B001不要使用bare `except:`，它还可以捕捉意外事件，如内存错误、中断、系统退出等等。使用`except Exception:`。如果您确定自己在做什么，请使用`except BaseException:`。 

</code></pre>
<h4>References</h4>
<section class="footnotes">
<ol>
<li id="fn-1"><p>https://www.python.org/dev/peps/pep-0008/<a href="#fnref-1" class="footnote">&#8617;</a></p></li>
</ol>
</section>

    </section>
</article>
